server.port=8085
spring.thymeleaf.cache=false
spring.datasource.generate-unique-name=false

# MongoDB properties
spring.data.mongodb.uri=mongodb+srv://tacocloud:abcd4321@cluster0.s0fko.mongodb.net/tacoclouddb
# spring.data.mongodb.uri=mongodb+srv://my_atlas_user:tkarms77@cluster0.s0fko.mongodb.net/tacoclouddb
# ${MONGODB_PASSWORD}/
taco.orders.pageSize=10


